"""
Zalo Socket Protocol Facade
This module re-exports all constants, frame structures, attach builders,
packet builders, and parsers to maintain 100% backward compatibility with
existing code while maintaining a clean modular architecture internally.
"""

import logging

from core.socket.constants import (
    CKSUM_MAGIC,
    MAGIC_CHECKSUM_XOR,
    XK,
    FRAME_TYPE_CONTROL,
    FRAME_TYPE_DATA,
    FRAME_TYPE_KEY_EXCHANGE,
    FRAME_TYPE_HANDSHAKE,
    CMD_PING,
    SUB_PING,
    CMD_GROUP_MSG,
    SUB_GROUP_MSG,
    CMD_1TO1_MSG,
    SUB_1TO1_MSG,
    SUB_PHOTO_MSG,
    SUB_DOODLE_MSG,
    SUB_PHOTO_ATTACH_MSG,
    SUB_ATTACH_MSG,
    SUB_VIDEO_MSG,
    SUB_STICKER_MSG,
    SUB_LOCATION_MSG,
    SUB_FILE_MSG,
    SUB_CONTACT_MSG,
    CMD_REACTION_PUSH,
    SUB_REACTION_PUSH,
    CMD_REACTION_ACTION,
    SUB_REACTION_ACTION,
    CMD_GROUP_TYPING,
    SUB_GROUP_TYPING,
    CMD_1TO1_TYPING,
    SUB_1TO1_TYPING,
    CMD_GROUP_PREPARE,
    SUB_GROUP_PREPARE,
    CMD_GROUP_SYNC_BROADCAST,
    SUB_GROUP_SYNC,
    CMD_DELIVERY_RECEIPT,
    SUB_DELIVERY_RECEIPT,
    CMD_1TO1_INCOMING,
    CMD_REMOVE_MEMBER,
    SUB_REMOVE_MEMBER,
    CMD_KICK_MEMBER,
    SUB_KICK_MEMBER,
    CMD_DISBAND_GROUP,
    SUB_DISBAND_GROUP,
    CMD_BLOCK_GROUP_MEMBER,
    SUB_BLOCK_GROUP_MEMBER,
    CMD_BLOCK_USER,
    SUB_BLOCK_USER,
    CMD_ADD_MEMBER,
    SUB_ADD_MEMBER,
    CMD_LEAVE_GROUP,
    SUB_LEAVE_GROUP,
    CMD_LEAVE_GROUP_225,
    SUB_LEAVE_GROUP_225,
    CMD_LEAVE_GROUP_239,
    SUB_LEAVE_GROUP_239,
    CMD_JOIN_GROUP,
    SUB_JOIN_GROUP,
    CMD_JOIN_GROUP_INVITE,
    SUB_JOIN_GROUP_INVITE,
    CMD_REQUEST_JOIN_GROUP,
    SUB_REQUEST_JOIN_GROUP,
    CMD_GROUP_LINK_INFO,
    SUB_GROUP_LINK_INFO,
    CMD_JOIN_GROUP_BY_LINK,
    SUB_JOIN_GROUP_BY_LINK,
    CMD_PIN_TOPIC,
    SUB_PIN_TOPIC,
    CMD_UNPIN_TOPIC,
    SUB_UNPIN_TOPIC,
    CMD_CREATE_POLL,
    SUB_CREATE_POLL,
    CMD_RECALL_MSG_GROUP,
    SUB_RECALL_MSG_GROUP,
    CMD_RECALL_MSG_1TO1,
    SUB_RECALL_MSG_1TO1,
    CMD_DELETE_MSG,
    SUB_DELETE_MSG,
    CMD_BLOCK_USER_1TO1,
    SUB_BLOCK_USER_1TO1,
    CMD_UNBLOCK_USER_1TO1,
    SUB_UNBLOCK_USER_1TO1,
)

from core.socket.crypto import (
    encrypt_aes_gcm,
    decrypt_aes_gcm,
    encrypt_e2ee_cbc,
    decrypt_e2ee_cbc,
    DEFAULT_XK,
)

from core.socket.frame import (
    INNER_HEADER_FORMAT,
    INNER_HEADER_SIZE,
    InnerPacketHeader,
    OuterFrame,
    compute_checksum,
    xor_encode_d3,
    xor_decode_d3,
    dekey,
    xor_enc,
    build_outer_frame,
)

from core.socket.attach import (
    build_photo_attach,
    build_video_attach,
    build_sticker_attach,
    build_location_attach,
    build_file_attach,
    build_contact_attach,
)

from core.socket.builder import (
    u16_len,
    merge_styles,
    parse_formatted_text,
    build_d3_payload_group,
    build_d3_json,
    build_d3_payload_1to1,
    build_d3_payload_1to1_styled,
    build_d3_payload_1to1_rtf,
    build_ping_packet,
    build_typing_packet,
    build_group_message_packet,
    build_1to1_message_packet,
    build_photo_binary_payload,
    build_photo_message_packet,
    build_video_binary_payload,
    build_video_message_packet,
    build_reaction_packet,
    build_pin_topic_packet,
    build_unpin_topic_packet,
    build_fetch_pinned_topics_packet,
    build_cmd_1705_packet,
    build_disband_242_packet,
    build_disband_group_packet,
    build_disband_test_frame,
    build_remove_member_packet,
    build_kick_member_packet,
    build_block_group_member_packet,
    build_block_user_packet,
    build_unblock_user_packet,
    build_leave_group_packet,
    build_leave_group_225_packet,
    build_leave_group_239_packet,
    build_create_poll_packet,
    build_join_group_by_link_901_packet,
    build_preview_link_901_packet,
    build_query_group_906_packet,
    build_query_user_profile_151_packet,
    build_recall_message_packet,
    build_delete_message_packet,
    build_add_member_packet,
    build_join_group_packet,
    build_join_group_invite_packet,
    build_request_join_group_packet,
    build_group_link_info_packet,
    build_join_group_by_link_packet,
    build_join_group_2000_packet,
)

from core.socket.parser import (
    parse_d3_compressed_json,
    parse_incoming_frame,
    parse_incoming_messages_payload,
    parse_group_sync_1867,
    parse_delivery_receipt_202,
    parse_incoming_reactions_1785,
)

logger = logging.getLogger('core.socket.protocol')
